### ISSUE TITLE
[Feature Request] Support Typescirpt index.d.ts file for all shared components

### ISSUE THREAD

**Issue by ultralabed** [trendmicro-frontend/tonic-ui#161] opened 2020-06-12 18:04 UTC

**Comment by AnupriyaSaxenas** [comment] 2020-06-22 13:58
We created types for theme in our React application that uses Typescript. Some issues are not identified by Typescript because of bracket notation. Example:
`theme.colors["red:20"] //This should not give a typescript error and doesn't and works as expected`
`theme.colors["gsdfgn"] //This should give me a typescript error but doesn't`
The problem is we can't use keys like "red:20" without bracket notation and if we use bracket notation, typescript doesn't throw errors for any invalid values. 
With dot notation we get typescript errors if we try to access any random value:
`theme.colors.gsdfgn //This gives the typescript error and works as expected`

**Comment by cheton** [comment] 2021-11-23 10:16
Close this issue because we don't have resource for adding TypeScript support so far.

**Closed as completed by cheton** 2021-11-23 10:16 UTC
Labels: 🎉 feature (enhancement)
